// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChmKXGkqvHqJa9jXrsZyjaEjLaagjONSI',
    appId: '1:434551183952:web:d8baacdf61a77171108f55',
    messagingSenderId: '434551183952',
    projectId: 'englishapp-3fe7d',
    authDomain: 'englishapp-3fe7d.firebaseapp.com',
    storageBucket: 'englishapp-3fe7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA8x76fPcVEsq7rKlpr8Q8FsNK46tnnVY',
    appId: '1:434551183952:android:cd5a538e010cf4c8108f55',
    messagingSenderId: '434551183952',
    projectId: 'englishapp-3fe7d',
    storageBucket: 'englishapp-3fe7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIf-KMgkNLq6gAci5x8AyPvs7JpXfLD2g',
    appId: '1:434551183952:ios:91163efd88edd483108f55',
    messagingSenderId: '434551183952',
    projectId: 'englishapp-3fe7d',
    storageBucket: 'englishapp-3fe7d.firebasestorage.app',
    iosBundleId: 'com.example.newone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIf-KMgkNLq6gAci5x8AyPvs7JpXfLD2g',
    appId: '1:434551183952:ios:91163efd88edd483108f55',
    messagingSenderId: '434551183952',
    projectId: 'englishapp-3fe7d',
    storageBucket: 'englishapp-3fe7d.firebasestorage.app',
    iosBundleId: 'com.example.newone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChmKXGkqvHqJa9jXrsZyjaEjLaagjONSI',
    appId: '1:434551183952:web:187f9f1b038270e4108f55',
    messagingSenderId: '434551183952',
    projectId: 'englishapp-3fe7d',
    authDomain: 'englishapp-3fe7d.firebaseapp.com',
    storageBucket: 'englishapp-3fe7d.firebasestorage.app',
  );
}
